// Template types and utilities

export type Template = {
  id: string; // must match backend registry
  title: string;
  tagline?: string;
  category: "Bots" | "Dashboards" | "E‑commerce" | "Ops" | "Auth" | "Other";
  difficulty?: "Beginner" | "Intermediate" | "Advanced";
  badges?: string[]; // e.g., ["New", "Popular"]
  hero?: string; // img url
  gallery?: string[]; // more screenshots
  description?: string;
  bullets?: string[];
  technologies?: string[]; // Technology tags shown at bottom
  setupTime?: string; // e.g., "20-30 min"
  actions?: {
    behavior: "wizard" | "scaffold"; // where the CTA should go
    path?: string; // e.g., "/setup"
    api?: string; // e.g., "/api/scaffold"
  };
};

// Local fallback registry (keep in sync with server)
const fallbackRegistry: Template[] = [
  {
    id: "analytics-dashboard",
    title: "Analytics Dashboard",
    tagline: "Real-time business analytics with custom KPI tracking.",
    category: "Dashboards",
    difficulty: "Advanced",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Real-time business analytics with custom KPI tracking.",
    bullets: ["Real-time data", "Custom KPIs", "Interactive charts"],
    technologies: ["Database", "Charting library"],
    setupTime: "20-30 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "data-sync-tool",
    title: "Data Sync Tool",
    tagline: "Synchronize data between multiple systems automatically.",
    category: "Dashboards",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Synchronize data between multiple systems automatically.",
    bullets: ["Multi-platform sync", "Conflict resolution", "Scheduled syncing"],
    technologies: ["APIs", "Scheduler"],
    setupTime: "15-20 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "data-sync-warehouse",
    title: "Data Sync Warehouse",
    tagline: "Sync data to your data warehouse with automated ETL pipelines.",
    category: "Dashboards",
    difficulty: "Advanced",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Enterprise-grade data warehouse synchronization with ETL pipelines.",
    bullets: ["Multi-source ingestion", "Automated transformations", "Real-time or scheduled sync"],
    technologies: ["Snowflake", "BigQuery", "ETL"],
    setupTime: "25-35 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "report-generator",
    title: "Report Generator",
    tagline: "Generate custom reports from your data sources.",
    category: "Dashboards",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Generate custom reports from your data sources.",
    bullets: ["Template library", "PDF generation", "Data visualization"],
    technologies: ["Database", "PDF library"],
    setupTime: "10-15 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "workflow-automation",
    title: "Workflow Automation",
    tagline: "Automate business processes with custom triggers and actions.",
    category: "Ops",
    difficulty: "Advanced",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Automate business processes with custom triggers and actions.",
    bullets: ["Visual workflow builder", "Custom triggers", "Multi-step automation"],
    technologies: ["Workflow engine", "APIs"],
    setupTime: "20-30 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    tagline: "Track business expenses with receipt scanning and reporting.",
    category: "Ops",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Track business expenses with receipt scanning and reporting.",
    bullets: ["Receipt scanning", "Expense categorization", "Monthly reports"],
    technologies: ["OCR", "Database", "Reporting"],
    setupTime: "15-20 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "appointment-booker",
    title: "Appointment Booker",
    tagline: "Books meetings, handles reschedules and reminders.",
    category: "Bots",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Books meetings, handles reschedules and reminders.",
    bullets: ["Calendar integration", "Automated reminders", "Reschedule handling"],
    technologies: ["Calendar API", "Email"],
    setupTime: "10-15 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "customer-support-widget",
    title: "Customer Support Widget",
    tagline: "AI-powered customer support with ticket escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "AI-powered customer support with ticket escalation.",
    bullets: ["AI chat assistant", "Ticket management", "Real-time support"],
    technologies: ["Support platform", "AI API"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "lead-qualification-bot",
    title: "Lead Qualification Bot",
    tagline: "Qualifies leads through intelligent conversations and scoring.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Qualifies leads through intelligent conversations and scoring.",
    bullets: ["Conversational AI", "Lead scoring", "CRM integration"],
    technologies: ["CRM", "AI API"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "zapier-intercom-integration",
    title: "Integration - Zapier x Intercom vibe",
    tagline: "Trigger zaps from conversations and sync contact events.",
    category: "Other",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Trigger zaps from conversations and sync contact events.",
    bullets: ["Preload actions for contact creation, tag sync, and alerting. Ships with example zaps and Intercom snippets"],
    technologies: ["Zapier", "Intercom"],
    setupTime: "5-10 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "social-media-scheduler",
    title: "Social Media Scheduler",
    tagline: "Schedule and manage posts across multiple platforms.",
    category: "E‑commerce",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Schedule and manage posts across multiple platforms.",
    bullets: ["Multi-platform posting", "Content calendar", "Analytics tracking"],
    technologies: ["Twitter/X", "Instagram/Facebook", "LinkedIn"],
    setupTime: "8-12 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "email-campaign-builder",
    title: "Email Campaign Builder",
    tagline: "Create and send personalized email campaigns with A/B testing.",
    category: "E‑commerce",
    difficulty: "Advanced",
    badges: ["Advanced"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Create and send personalized email campaigns with A/B testing.",
    bullets: ["Drag & drop editor", "A/B testing", "Segmentation"],
    technologies: ["Email provider (SendGrid/Mailgun/Postmark)", "Contacts DB/CRM"],
    setupTime: "20-30 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "inventory-manager",
    title: "Inventory Manager",
    tagline: "Track inventory levels with automated reorder alerts.",
    category: "Ops",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Track inventory levels with automated reorder alerts.",
    bullets: ["Stock tracking", "Low stock alerts", "Supplier management"],
    technologies: ["Postgres/Supabase", "Email/Slack for alerts"],
    setupTime: "10-15 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "customer-support-bot",
    title: "Customer Support Bot",
    tagline: "AI-powered support agent for FAQs and escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "AI-powered support agent for FAQs and escalation.",
    bullets: ["FAQ handling", "Escalation", "Transcript logging"],
    technologies: ["Knowledge base", "Support platform"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "agent-support-bot",
    title: "Agent + Support Bot",
    tagline: "Customer-facing AI with memory, tools, and clean escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Advanced"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Customer-facing AI with memory, tools, and clean escalation.",
    bullets: ["Production-ready support agent that answers FAQs, collects context, hands off to humans gracefully, and logs transcripts"],
    technologies: ["Knowledge base (Notion/Docs)", "Slack", "Email"],
    setupTime: "15-25 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "bio-lead-qualifier",
    title: "Flow + Lead Qualifier",
    tagline: "Capture, score, and route leads to the right pipeline.",
    category: "Bots",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Capture, score, and route leads to the right pipeline.",
    bullets: ["Conversational intake that scores intent, enriches with firmographics, and books meetings or sends handoffs"],
    technologies: ["CRM (HubSpot/Salesforce)", "Calendly"],
    setupTime: "10-15 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "data-doc-sync",
    title: "Data + Docs Sync",
    tagline: "Keep your docs and answers in sync with a repo or DB.",
    category: "Ops",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Keep your docs and answers in sync with a repo or DB.",
    bullets: ["Includes markdown/Notion and keeps embeddings fresh on a schedule. Ships with pruning + re-crawl policies"],
    technologies: ["GitHub/GitLab", "Postgres/Supabase"],
    setupTime: "8-12 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
];

export function getTemplateById(id: string): Template | undefined {
  return fallbackRegistry.find(template => template.id === id);
}

export { fallbackRegistry };
