// Template types and utilities

export type Template = {
  id: string; // must match backend registry
  title: string;
  tagline?: string;
  category: "Bots" | "Dashboards" | "E‑commerce" | "Ops" | "Auth" | "Other";
  difficulty?: "Beginner" | "Intermediate" | "Advanced";
  badges?: string[]; // e.g., ["New", "Popular"]
  hero?: string; // img url
  gallery?: string[]; // more screenshots
  description?: string;
  bullets?: string[];
  technologies?: string[]; // Technology tags shown at bottom
  setupTime?: string; // e.g., "20-30 min"
  actions?: {
    behavior: "wizard" | "scaffold"; // where the CTA should go
    path?: string; // e.g., "/setup"
    api?: string; // e.g., "/api/scaffold"
  };
};

// Local fallback registry (keep in sync with server)
// Ordered by: Free (Beginner) → Pro (Intermediate) → Business (Advanced)
const fallbackRegistry: Template[] = [
  // ===== FREE TEMPLATES (Beginner) =====
  {
    id: "report-generator",
    title: "Report Generator",
    tagline: "Generate custom reports from your data sources.",
    category: "Dashboards",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Generate custom reports from your data sources.",
    bullets: ["Template library", "PDF generation", "Data visualization"],
    technologies: ["Database", "PDF library"],
    setupTime: "10-15 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "appointment-booker",
    title: "Appointment Booker",
    tagline: "Book meetings, handle reschedules and reminders.",
    category: "Bots",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Books meetings, handles reschedules and reminders.",
    bullets: ["Calendar integration", "Automated reminders", "Reschedule handling"],
    technologies: ["Calendar API", "Email"],
    setupTime: "10-15 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "inventory-manager",
    title: "Inventory Manager",
    tagline: "Track inventory levels with automated reorder alerts.",
    category: "Ops",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Track inventory levels with automated reorder alerts.",
    bullets: ["Stock tracking", "Low stock alerts", "Supplier management"],
    technologies: ["Postgres/Supabase", "Email/Slack for alerts"],
    setupTime: "10-15 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "social-media-scheduler",
    title: "Social Media Scheduler",
    tagline: "Schedule and manage posts across multiple platforms.",
    category: "E‑commerce",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Schedule and manage posts across multiple platforms.",
    bullets: ["Multi-platform posting", "Content calendar", "Analytics tracking"],
    technologies: ["Twitter/X", "Instagram/Facebook", "LinkedIn"],
    setupTime: "8-12 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "email-campaign-builder-free",
    title: "Email Campaign Builder",
    tagline: "Create and send personalized email campaigns.",
    category: "E‑commerce",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Create and send personalized email campaigns.",
    bullets: ["Drag & drop editor", "Template library", "Basic analytics"],
    technologies: ["Email provider (SendGrid/Mailgun/Postmark)"],
    setupTime: "10-15 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "zapier-intercom-integration",
    title: "Zapier x Intercom",
    tagline: "Preload actions for contact creation, text sync, and alerting.",
    category: "Other",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Trigger zaps from conversations and sync contact events.",
    bullets: ["Preload actions for contact creation, tag sync, and alerting"],
    technologies: ["Zapier", "Intercom"],
    setupTime: "5-10 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "faq-bot",
    title: "FAQ Bot",
    tagline: "Answer common questions with AI-powered responses.",
    category: "Bots",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Answer common questions with AI-powered responses.",
    bullets: ["Knowledge base integration", "Natural language processing", "24/7 availability"],
    technologies: ["AI API", "Knowledge base"],
    setupTime: "10-15 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  // ===== PRO TEMPLATES (Intermediate) =====
  {
    id: "data-sync-tool",
    title: "Data Sync Tool",
    tagline: "Synchronize data between multiple systems automatically.",
    category: "Dashboards",
    difficulty: "Intermediate",
    badges: ["Popular", "Pro"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Synchronize data between multiple systems automatically.",
    bullets: ["Multi-platform sync", "Conflict resolution", "Scheduled syncing"],
    technologies: ["APIs", "Scheduler"],
    setupTime: "15-20 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    tagline: "Track business expenses with receipt scanning and reporting.",
    category: "Ops",
    difficulty: "Intermediate",
    badges: ["Popular", "Pro"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Track business expenses with receipt scanning and reporting.",
    bullets: ["Receipt scanning", "Expense categorization", "Monthly reports"],
    technologies: ["OCR", "Database", "Reporting"],
    setupTime: "15-20 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "customer-support-widget",
    title: "Customer Support Widget",
    tagline: "AI-powered customer support with ticket escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular", "Pro"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "AI-powered customer support with ticket escalation.",
    bullets: ["AI chat assistant", "Ticket management", "Real-time support"],
    technologies: ["Support platform", "AI API"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "customer-support-bot",
    title: "Customer Support Bot",
    tagline: "AI-powered support agent for FAQs and escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular", "Pro"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "AI-powered support agent for FAQs and escalation.",
    bullets: ["FAQ handling", "Escalation", "Transcript logging"],
    technologies: ["Knowledge base", "Support platform"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "lead-qualification-bot",
    title: "Lead Qualification Bot",
    tagline: "Qualifies leads through intelligent conversations and scoring.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular", "Pro"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Qualifies leads through intelligent conversations and scoring.",
    bullets: ["Conversational AI", "Lead scoring", "CRM integration"],
    technologies: ["CRM", "AI API"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "onboarding-bot",
    title: "Onboarding Bot",
    tagline: "Guide new users through your product with personalized flows.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular", "Pro"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Guide new users through your product with personalized flows.",
    bullets: ["Interactive walkthroughs", "Progress tracking", "Personalization"],
    technologies: ["AI API", "User database"],
    setupTime: "15-20 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  // ===== BUSINESS TEMPLATES (Advanced) =====
  {
    id: "analytics-dashboard",
    title: "Analytics Dashboard",
    tagline: "Real-time business analytics with custom KPIs and tracking.",
    category: "Dashboards",
    difficulty: "Advanced",
    badges: ["Popular", "Business"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Real-time business analytics with custom KPI tracking.",
    bullets: ["Real-time data", "Custom KPIs", "Interactive charts"],
    technologies: ["Database", "Charting library"],
    setupTime: "20-30 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "workflow-automation",
    title: "Workflow Automation",
    tagline: "Automate business processes with custom triggers and actions.",
    category: "Ops",
    difficulty: "Advanced",
    badges: ["Popular", "Business"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Automate business processes with custom triggers and actions.",
    bullets: ["Visual workflow builder", "Custom triggers", "Multi-step automation"],
    technologies: ["Workflow engine", "APIs"],
    setupTime: "20-30 min",
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "data-sync-warehouse",
    title: "Data Sync Warehouse",
    tagline: "Sync data to your data warehouse with automated ETL pipelines.",
    category: "Dashboards",
    difficulty: "Advanced",
    badges: ["Popular", "Business"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Enterprise-grade data warehouse synchronization with ETL pipelines.",
    bullets: ["Multi-source ingestion", "Automated transformations", "Real-time or scheduled sync"],
    technologies: ["Snowflake", "BigQuery", "ETL"],
    setupTime: "25-35 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "feedback-survey-bot",
    title: "Feedback Survey Bot",
    tagline: "Collect and analyze customer feedback with AI insights.",
    category: "Bots",
    difficulty: "Advanced",
    badges: ["Advanced", "Business"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Collect and analyze customer feedback with AI-powered insights.",
    bullets: ["Survey builder", "Sentiment analysis", "Trend reporting"],
    technologies: ["AI API", "Analytics"],
    setupTime: "20-25 min",
    actions: { behavior: "wizard", path: "/setup" },
  },
];

export function getTemplateById(id: string): Template | undefined {
  return fallbackRegistry.find(template => template.id === id);
}

export { fallbackRegistry };
