import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Template registry (keep in sync with client fallback)
const templates = [
  {
    id: "analytics-dashboard",
    title: "Analytics Dashboard",
    tagline: "Real-time business analytics with custom KPIs and tracking.",
    category: "Dashboards",
    difficulty: "Advanced",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png", "/assets/template-card-design.png"],
    description: "Real-time data visualization with custom KPIs, charting library, and interactive charts.",
    features: ["Real-time data", "Custom KPIs", "Interactive charts"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "data-sync-tool",
    title: "Data Sync Tool",
    tagline: "Synchronize data between multiple systems automatically.",
    category: "Ops",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Multi-platform sync, conflict resolution, and scheduled syncing for seamless data flow.",
    features: ["Multi-platform sync", "Conflict resolution", "Scheduled syncing"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "report-generator",
    title: "Report Generator",
    tagline: "Generate custom reports from your data sources.",
    category: "Dashboards",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Template library, PDF generation, and data visualization for comprehensive reporting.",
    features: ["Template library", "PDF generation", "Data visualization"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "workflow-automation",
    title: "Workflow Automation",
    tagline: "Automate business processes with custom triggers and actions.",
    category: "Ops",
    difficulty: "Advanced",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Visual workflow builder, custom triggers, and multi-step automation for streamlined operations.",
    features: ["Visual workflow builder", "Custom triggers", "Multi-step automation"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    tagline: "Track business expenses with receipt scanning and reporting.",
    category: "Ops",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Receipt scanning, expense categorization, and monthly reports for financial management.",
    features: ["Receipt scanning", "Expense categorization", "Monthly reports"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "appointment-booker",
    title: "Appointment Booker",
    tagline: "Book meetings, handle reschedules and reminders.",
    category: "Bots",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Calendar integration, automated reminders, and reschedule handling for seamless booking.",
    features: ["Calendar integration", "Automated reminders", "Reschedule handling"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "customer-support-widget",
    title: "Customer Support Widget",
    tagline: "AI-powered customer support with ticket escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "AI chat assistant, ticket management, and real-time support for customer satisfaction.",
    features: ["AI chat assistant", "Ticket management", "Real-time support"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "lead-qualification-bot",
    title: "Lead Qualification Bot",
    tagline: "Qualifies leads through intelligent conversations and scoring.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Conversational AI, lead scoring, and CRM integration for effective lead qualification.",
    features: ["Conversational AI", "Lead scoring", "CRM integration"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "customer-support-bot",
    title: "Customer Support Bot",
    tagline: "AI-powered support agent for FAQs and escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Popular"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "FAQ handling, escalation, and transcript logging for comprehensive support.",
    features: ["FAQ handling", "Escalation", "Transcript logging"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "agent-support-bot",
    title: "Agent + Support Bot",
    tagline: "Customer-facing AI with memory, tools, and clean escalation.",
    category: "Bots",
    difficulty: "Intermediate",
    badges: ["Advanced"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Production-ready support agent with memory, context, and seamless human handoff.",
    features: ["Knowledge base (Notion/Docs)", "Slack", "Email"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "bio-lead-qualifier",
    title: "Flow + Lead Qualifier",
    tagline: "Capture, score, and route leads to the right pipeline.",
    category: "Bots",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Conversational intake that scores intent, enriches with firmographics, and books meetings or sends handoffs.",
    features: ["CRM (HubSpot/Salesforce)", "Calendly"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "data-doc-sync",
    title: "Data + Docs Sync",
    tagline: "Keep your docs and answers in sync with a repo or DB.",
    category: "Ops",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Keep your docs and answers in sync with a repo or DB.",
    features: ["GitHub/GitLab", "Postgres/Supabase"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "zapier-intercom-integration",
    title: "Integration - Zapier x Intercom vibe",
    tagline: "Preload actions for contact creation, text sync, and alerting.",
    category: "Other",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Ships with example zaps and Intercom snippets for easy integration setup.",
    features: ["Zapier", "Intercom"],
    actions: { behavior: "wizard", path: "/setup" },
  },
  {
    id: "social-media-scheduler",
    title: "Social Media Scheduler",
    tagline: "Schedule and manage posts across multiple platforms.",
    category: "E‑commerce",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Multi-platform posting, content calendar, and analytics tracking for social media management.",
    features: ["Multi-platform posting", "Content calendar", "Analytics tracking"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "email-campaign-builder",
    title: "Email Campaign Builder",
    tagline: "Create and send personalized email campaigns with A/B testing.",
    category: "E‑commerce",
    difficulty: "Advanced",
    badges: ["Advanced"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Drag & drop editor, A/B testing, and segmentation for effective email marketing.",
    features: ["Drag & drop editor", "A/B testing", "Segmentation"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
  {
    id: "inventory-manager",
    title: "Inventory Manager",
    tagline: "Track inventory levels with automated reorder alerts.",
    category: "Ops",
    difficulty: "Beginner",
    badges: ["Easy"],
    hero: "/assets/template-card-design.png",
    gallery: ["/assets/template-card-design.png"],
    description: "Stock tracking, low stock alerts, and supplier management for efficient inventory control.",
    features: ["Stock tracking", "Low stock alerts", "Supplier management"],
    actions: { behavior: "scaffold", api: "/api/scaffold" },
  },
];

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (req.method === 'GET') {
      return new Response(
        JSON.stringify({ ok: true, data: templates }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        },
      )
    }

    return new Response(
      JSON.stringify({ ok: false, error: 'Method not allowed' }),
      {
        status: 405,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    )
  } catch (error) {
    return new Response(
      JSON.stringify({ ok: false, error: error.message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    )
  }
})
